"""add agent mirror tables

Revision ID: 31fd565263bd
Revises: c3d4e5f6g7h8
Create Date: 2026-08-05 13:09:23.019706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fd565263bd'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('auto_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_workflows_auto_id'), 'agent_workflows', ['auto_id'], unique=True)
    op.create_index(op.f('ix_agent_workflows_id'), 'agent_workflows', ['id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_run_id', sa.String(length=64), nullable=False),
    sa.Column('auto_workflow_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('auto_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('timeline_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['agent_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_auto_created_at'), 'agent_runs', ['auto_created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_auto_run_id'), 'agent_runs', ['auto_run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_auto_workflow_id'), 'agent_runs', ['auto_workflow_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index('ix_agent_runs_workflow_created', 'agent_runs', ['auto_workflow_id', 'auto_created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_workflow_id'), 'agent_runs', ['workflow_id'], unique=False)
    op.create_table('agent_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_activity_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=128), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('step_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_activities_auto_activity_id'), 'agent_activities', ['auto_activity_id'], unique=True)
    op.create_index(op.f('ix_agent_activities_id'), 'agent_activities', ['id'], unique=False)
    op.create_index(op.f('ix_agent_activities_run_id'), 'agent_activities', ['run_id'], unique=False)
    op.create_index('ix_agent_activities_run_sequence', 'agent_activities', ['run_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_agent_activities_status'), 'agent_activities', ['status'], unique=False)
    # NOTE: autogenerate also proposed dropping two audit_logs indexes and the
    # items.priority/items.status columns. Those are pre-existing drift between
    # the template's models and its earlier migrations, not part of this change.
    # Removed deliberately — this migration only adds the agent mirror tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Mirror of upgrade(): only the agent tables are removed. The items columns
    # and audit_logs indexes were never touched here, so they are not recreated.
    op.drop_index(op.f('ix_agent_activities_status'), table_name='agent_activities')
    op.drop_index('ix_agent_activities_run_sequence', table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_run_id'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_id'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_auto_activity_id'), table_name='agent_activities')
    op.drop_table('agent_activities')
    op.drop_index(op.f('ix_agent_runs_workflow_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_workflow_created', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_auto_workflow_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_auto_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_auto_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_workflows_id'), table_name='agent_workflows')
    op.drop_index(op.f('ix_agent_workflows_auto_id'), table_name='agent_workflows')
    op.drop_table('agent_workflows')
    # ### end Alembic commands ###
