"""add timeline_error to agent_runs

Revision ID: 343723e5bc39
Revises: 31fd565263bd
Create Date: 2026-08-05 13:13:23.999817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343723e5bc39'
down_revision: Union[str, None] = '31fd565263bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('timeline_error', sa.Text(), nullable=True))
    # Autogenerate keeps re-proposing drops of two audit_logs indexes and the
    # items.priority/items.status columns. That is pre-existing template drift,
    # not part of this change. Removed deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'timeline_error')
    # ### end Alembic commands ###
