"""add activity artifact fields

Revision ID: 5fc02243f8d2
Revises: da14a2c80114
Create Date: 2026-08-05 14:06:22.646140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc02243f8d2'
down_revision: Union[str, None] = 'da14a2c80114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_activities', sa.Column('output_files', sa.JSON(), nullable=True))
    op.add_column('agent_activities', sa.Column('artifact_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_activities', 'artifact_data')
    op.drop_column('agent_activities', 'output_files')
    # ### end Alembic commands ###
