"""add policy tables

Revision ID: 98e55a054b00
Revises: 343723e5bc39
Create Date: 2026-08-05 13:50:51.278464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e55a054b00'
down_revision: Union[str, None] = '343723e5bc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_key'), 'policies', ['key'], unique=True)
    op.create_table('policy_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('policy_key', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_changes_changed_at'), 'policy_changes', ['changed_at'], unique=False)
    op.create_index(op.f('ix_policy_changes_id'), 'policy_changes', ['id'], unique=False)
    op.create_index(op.f('ix_policy_changes_policy_id'), 'policy_changes', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_changes_policy_key'), 'policy_changes', ['policy_key'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_key', sa.String(length=64), nullable=True),
    sa.Column('policy_name', sa.String(length=255), nullable=True),
    sa.Column('subject_ref', sa.String(length=128), nullable=True),
    sa.Column('subject_type', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('threshold_in_force', sa.JSON(), nullable=True),
    sa.Column('observed_values', sa.JSON(), nullable=True),
    sa.Column('auto_run_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_name', sa.String(length=255), nullable=True),
    sa.Column('step_name', sa.String(length=255), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['agent_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_activity_id'), 'policy_evaluations', ['activity_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_auto_run_id'), 'policy_evaluations', ['auto_run_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_evaluated_at'), 'policy_evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_outcome'), 'policy_evaluations', ['outcome'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_key'), 'policy_evaluations', ['policy_key'], unique=False)
    op.create_index('ix_policy_evaluations_policy_time', 'policy_evaluations', ['policy_key', 'evaluated_at'], unique=False)
    op.create_index('ix_policy_evaluations_run_policy', 'policy_evaluations', ['auto_run_id', 'policy_key'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_subject_ref'), 'policy_evaluations', ['subject_ref'], unique=False)
    # Autogenerate keeps proposing drops of two audit_logs indexes and the
    # items.priority/items.status columns. That is pre-existing template
    # drift, not part of this change. Removed deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_evaluations_subject_ref'), table_name='policy_evaluations')
    op.drop_index('ix_policy_evaluations_run_policy', table_name='policy_evaluations')
    op.drop_index('ix_policy_evaluations_policy_time', table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_policy_key'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_outcome'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_evaluated_at'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_auto_run_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_activity_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_policy_changes_policy_key'), table_name='policy_changes')
    op.drop_index(op.f('ix_policy_changes_policy_id'), table_name='policy_changes')
    op.drop_index(op.f('ix_policy_changes_id'), table_name='policy_changes')
    op.drop_index(op.f('ix_policy_changes_changed_at'), table_name='policy_changes')
    op.drop_table('policy_changes')
    op.drop_index(op.f('ix_policies_key'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
